# Generated by Django 3.2.15 on 2022-12-29 15:56

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('create_ad', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.CharField(default=False, max_length=10)),
                ('car_brand', models.CharField(max_length=100)),
                ('to_0', models.CharField(max_length=100)),
                ('to_0_price', models.IntegerField(null=True)),
                ('to_1', models.CharField(max_length=100)),
                ('to_1_price', models.IntegerField(null=True)),
                ('to_2', models.CharField(max_length=100)),
                ('to_2_price', models.IntegerField(null=True)),
                ('to_3', models.CharField(max_length=100)),
                ('to_3_price', models.IntegerField(null=True)),
                ('to_4', models.CharField(max_length=100)),
                ('to_4_price', models.IntegerField(null=True)),
                ('to_5', models.CharField(max_length=100)),
                ('to_5_price', models.IntegerField(null=True)),
                ('to_6', models.CharField(max_length=100)),
                ('to_6_price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('number_tm', models.IntegerField(verbose_name='Табельный номер')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='ava', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Управляющий',
                'verbose_name_plural': 'Управляющие',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_name', models.CharField(max_length=50, verbose_name='Названия компании')),
                ('country_of_manufacture', models.CharField(max_length=50, verbose_name='Страна производства')),
                ('date_of_foundation', models.CharField(max_length=50, verbose_name='Дата основания компании')),
                ('history', models.TextField(blank=True, null=True, verbose_name='История компании')),
                ('logo_manuf', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(blank=True, max_length=50, verbose_name='Название акции')),
                ('discount_amount', models.IntegerField(verbose_name='Размер скидки')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Shop_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('number_tm', models.IntegerField(verbose_name='Табельный номер')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='ava', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Менеджер по продажам',
                'verbose_name_plural': 'Менеджеры по продажам',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, verbose_name='Дата основания отдела')),
                ('name_team', models.CharField(max_length=50, verbose_name='Название отдела')),
                ('top_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.shop_manager', verbose_name='Сотрудник месяца')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название салона')),
                ('sity', models.CharField(max_length=50, verbose_name='Город')),
                ('location', models.CharField(max_length=50, verbose_name='Адрес')),
                ('square', models.IntegerField(blank=True, null=True, verbose_name='Площадь склада,м.кв')),
                ('number_of_seats', models.IntegerField(blank=True, null=True, verbose_name='Количество мест на складе')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_salon', verbose_name='Фото шоурума')),
                ('manager_shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.shop_manager', verbose_name='Менедер по продажам')),
                ('top_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.manager', verbose_name='Управляющий')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.AddField(
            model_name='shop_manager',
            name='manager_team',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.team', verbose_name='Подразделение'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, verbose_name='Дата записи  на ТО')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('car_model', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('type_of_repair', models.CharField(max_length=50, verbose_name='Вид технического обслуживания')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.stock', verbose_name='Выберите салон')),
            ],
            options={
                'verbose_name': 'Запись на сервис',
                'verbose_name_plural': 'Записи на сервисное обслуживание',
            },
        ),
        migrations.CreateModel(
            name='MothJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_journal', models.DateTimeField()),
                ('present_day_1', models.BooleanField(default=False)),
                ('present_day_2', models.BooleanField(default=False)),
                ('present_day_3', models.BooleanField(default=False)),
                ('present_day_4', models.BooleanField(default=False)),
                ('present_day_5', models.BooleanField(default=False)),
                ('present_day_6', models.BooleanField(default=False)),
                ('present_day_7', models.BooleanField(default=False)),
                ('present_day_8', models.BooleanField(default=False)),
                ('present_day_9', models.BooleanField(default=False)),
                ('present_day_10', models.BooleanField(default=False)),
                ('present_day_11', models.BooleanField(default=False)),
                ('present_day_12', models.BooleanField(default=False)),
                ('present_day_13', models.BooleanField(default=False)),
                ('present_day_14', models.BooleanField(default=False)),
                ('present_day_15', models.BooleanField(default=False)),
                ('present_day_16', models.BooleanField(default=False)),
                ('present_day_17', models.BooleanField(default=False)),
                ('present_day_18', models.BooleanField(default=False)),
                ('present_day_19', models.BooleanField(default=False)),
                ('present_day_20', models.BooleanField(default=False)),
                ('present_day_21', models.BooleanField(default=False)),
                ('present_day_22', models.BooleanField(default=False)),
                ('present_day_23', models.BooleanField(default=False)),
                ('present_day_24', models.BooleanField(default=False)),
                ('present_day_25', models.BooleanField(default=False)),
                ('present_day_26', models.BooleanField(default=False)),
                ('present_day_27', models.BooleanField(default=False)),
                ('present_day_28', models.BooleanField(default=False)),
                ('present_day_29', models.BooleanField(default=False)),
                ('present_day_30', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.shop_manager', unique_for_month='date', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Журнал учета рабочего времени',
                'verbose_name_plural': 'Журналы учета рабочего времени',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('last_name', models.CharField(max_length=100, verbose_name='Модель автомобиля')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='Вин номер')),
                ('car_class', models.CharField(blank=True, max_length=2, verbose_name='Класс автомобиля')),
                ('year_of_release', models.IntegerField(verbose_name='Год выпуска')),
                ('type_body', models.CharField(max_length=50, verbose_name='Тип кузова')),
                ('drive', models.CharField(max_length=50, verbose_name='Тип привода')),
                ('fuel', models.CharField(max_length=50, verbose_name='Вид топлива')),
                ('volume_engine', models.FloatField(verbose_name='Рабочий обьем,куб.см')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('number_of_seats', models.IntegerField(verbose_name='Колличество мест')),
                ('maximum_speed', models.IntegerField(verbose_name='Максю скорость,км/ч')),
                ('curb_weight', models.IntegerField(verbose_name='Снаряженная масса,кг')),
                ('euroncap', models.IntegerField(verbose_name='Рейтинг безопасности ')),
                ('price', models.IntegerField(verbose_name='Цена(y.e.)')),
                ('sale_price', models.IntegerField(blank=True, null=True, verbose_name='Цена c учетом скидки(y.e.)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image_car', verbose_name='Фото')),
                ('notes', models.TextField(blank=True, verbose_name='Доп. информация')),
                ('avtosalon_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.stock', verbose_name='Автосалон')),
                ('car_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.manufacture', verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
