# Generated by Django 3.2.15 on 2023-01-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='client_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
